/**
 * ✅ ROOT-LEVEL UNIVERSAL: Node Metadata System
 * 
 * This is the SINGLE SOURCE OF TRUTH for ALL node metadata.
 * 
 * Architecture Rules:
 * 1. ALL nodes MUST have metadata
 * 2. Metadata tracks origin, detection method, and annotations
 * 3. Uses standardized prefixes (not scattered _dslId, _autoInjected, etc.)
 * 4. Works for ALL nodes universally
 * 5. Enables AI to understand node context and help users
 * 
 * This ensures:
 * - Permanent metadata tracking for ALL nodes
 * - AI can understand where nodes came from
 * - AI can connect/highlight notes about nodes
 * - Universal solution (no batch fixes needed)
 */

/**
 * Node Origin Source
 * Tracks where the node came from
 */
export type NodeOriginSource = 
  | 'user'        // User explicitly mentioned in prompt
  | 'auto'        // Auto-detected from user intent
  | 'system'      // System-injected (safety nodes, error handlers)
  | 'planner'     // Generated by Smart Planner
  | 'dsl'         // Generated from DSL
  | 'injected'    // Auto-injected by system (safety, error handling)
  | 'expanded'    // Expanded from intent expansion
  | 'fallback';   // Fallback/default node

/**
 * Detection Approach
 * Tracks which method detected/created the node
 */
export type DetectionApproach =
  | 'planner'           // Smart Planner detected
  | 'dsl_generation'     // DSL Generator created
  | 'capability_match'  // Capability registry matched
  | 'operation_match'   // Operation-based matching
  | 'semantic_match'    // Semantic AI matching
  | 'keyword_match'     // Keyword matching
  | 'pattern_match'     // Pattern matching
  | 'registry_fallback' // Registry-based fallback
  | 'user_explicit'     // User explicitly mentioned
  | 'auto_injected'     // Auto-injected by system
  | 'safety_injection'  // Safety node injection
  | 'error_handling';   // Error handling injection

/**
 * Node Stage
 * Tracks which stage of workflow generation created the node
 */
export type NodeStage =
  | 'intent_analysis'      // Intent analysis stage
  | 'planner'              // Smart Planner stage
  | 'dsl_generation'       // DSL generation stage
  | 'dsl_compilation'      // DSL compilation stage
  | 'workflow_building'    // Workflow building stage
  | 'node_injection'       // Node injection stage
  | 'safety_injection'     // Safety node injection
  | 'error_handling'       // Error handling injection
  | 'validation'           // Validation stage
  | 'sanitization'         // Graph sanitization
  | 'optimization';         // Workflow optimization

/**
 * Node Annotation
 * Allows AI to add notes, highlights, and connections about nodes
 */
export interface NodeAnnotation {
  /**
   * Note text (what AI wants to highlight)
   */
  note: string;
  
  /**
   * Highlight type (for UI display)
   */
  highlightType?: 'info' | 'warning' | 'error' | 'success' | 'tip';
  
  /**
   * Connected node IDs (nodes related to this annotation)
   */
  connectedNodes?: string[];
  
  /**
   * Related fields (fields related to this annotation)
   */
  relatedFields?: string[];
  
  /**
   * Timestamp when annotation was created
   */
  timestamp: number;
  
  /**
   * AI model that created the annotation
   */
  createdBy?: string;
}

/**
 * ✅ UNIVERSAL: Node Metadata Interface
 * 
 * ALL nodes MUST have this metadata structure.
 * This replaces scattered prefixes like _dslId, _autoInjected, etc.
 */
export interface NodeMetadata {
  /**
   * Origin information
   */
  origin: {
    /**
     * Source of the node (user, auto, system, etc.)
     */
    source: NodeOriginSource;
    
    /**
     * Detection approach (how the node was detected/created)
     */
    approach: DetectionApproach;
    
    /**
   * Stage where node was created
   */
    stage: NodeStage;
    
    /**
     * Original prompt text that led to this node (if applicable)
     */
    originalPrompt?: string;
    
    /**
     * User intent that led to this node (if applicable)
     */
    userIntent?: string;
  };
  
  /**
   * DSL information (if node came from DSL)
   */
  dsl?: {
    /**
     * DSL ID (replaces _dslId prefix)
     */
    dslId: string;
    
    /**
     * DSL category (data_source, transformation, output)
     */
    category: 'data_source' | 'transformation' | 'output';
    
    /**
     * DSL operation
     */
    operation?: string;
  };
  
  /**
   * Auto-injection information (if node was auto-injected)
   */
  injection?: {
    /**
     * Whether node was auto-injected (replaces _autoInjected prefix)
     */
    autoInjected: boolean;
    
    /**
     * Reason for injection
     */
    reason: string;
    
    /**
     * Injection priority
     */
    priority?: number;
  };
  
  /**
   * AI mode information (for AI-generated fields)
   */
  aiMode?: {
    /**
     * Fields that are AI-generated (replaces _messageMode, _textMode, etc.)
     */
    aiGeneratedFields: string[];
    
    /**
     * AI model used for generation
     */
    aiModel?: string;
    
    /**
     * Generation timestamp
     */
    generatedAt?: number;
  };
  
  /**
   * Annotations (notes, highlights, connections)
   */
  annotations?: NodeAnnotation[];
  
  /**
   * Protection flag (if node should not be removed)
   */
  protected?: boolean;
  
  /**
   * Version information
   */
  version?: {
    /**
     * Schema version
     */
    schemaVersion: string;
    
    /**
     * Metadata version
     */
    metadataVersion: string;
  };
}

/**
 * ✅ UNIVERSAL: Metadata Prefix Constants
 * 
 * Standardized prefixes for metadata fields in node config.
 * These replace scattered prefixes like _dslId, _autoInjected, etc.
 */
export const METADATA_PREFIXES = {
  /**
   * Origin metadata prefix
   */
  ORIGIN: '_meta_origin',
  
  /**
   * DSL metadata prefix
   */
  DSL: '_meta_dsl',
  
  /**
   * Injection metadata prefix
   */
  INJECTION: '_meta_injection',
  
  /**
   * AI mode metadata prefix
   */
  AI_MODE: '_meta_ai_mode',
  
  /**
   * Annotations prefix
   */
  ANNOTATIONS: '_meta_annotations',
  
  /**
   * Version prefix
   */
  VERSION: '_meta_version',
} as const;

/**
 * ✅ UNIVERSAL: Metadata Helper Functions
 * 
 * These functions provide a clean API for working with node metadata.
 * They handle all the prefix management internally.
 */
export class NodeMetadataHelper {
  /**
   * Get metadata from node config
   */
  static getMetadata(node: { data?: { config?: Record<string, any> } }): NodeMetadata | null {
    const config = node.data?.config || {};
    
    // Check if new metadata format exists
    if (config[METADATA_PREFIXES.ORIGIN]) {
      return {
        origin: config[METADATA_PREFIXES.ORIGIN] || {},
        dsl: config[METADATA_PREFIXES.DSL],
        injection: config[METADATA_PREFIXES.INJECTION],
        aiMode: config[METADATA_PREFIXES.AI_MODE],
        annotations: config[METADATA_PREFIXES.ANNOTATIONS],
        protected: config.protected,
        version: config[METADATA_PREFIXES.VERSION],
      };
    }
    
    // Migrate old format to new format
    return this.migrateOldMetadata(config);
  }
  
  /**
   * Set metadata in node config
   */
  static setMetadata(
    node: { data?: { config?: Record<string, any> } },
    metadata: Partial<NodeMetadata>
  ): void {
    const config = node.data?.config || {};
    
    if (metadata.origin) {
      config[METADATA_PREFIXES.ORIGIN] = metadata.origin;
    }
    if (metadata.dsl) {
      config[METADATA_PREFIXES.DSL] = metadata.dsl;
    }
    if (metadata.injection) {
      config[METADATA_PREFIXES.INJECTION] = metadata.injection;
    }
    if (metadata.aiMode) {
      config[METADATA_PREFIXES.AI_MODE] = metadata.aiMode;
    }
    if (metadata.annotations) {
      config[METADATA_PREFIXES.ANNOTATIONS] = metadata.annotations;
    }
    if (metadata.protected !== undefined) {
      config.protected = metadata.protected;
    }
    if (metadata.version) {
      config[METADATA_PREFIXES.VERSION] = metadata.version;
    }
    
    // Ensure config exists
    if (!node.data) {
      node.data = { config: {} };
    }
    if (!node.data.config) {
      node.data.config = {};
    }
    
    // Merge into existing config
    Object.assign(node.data.config, config);
  }
  
  /**
   * Add annotation to node
   */
  static addAnnotation(
    node: { data?: { config?: Record<string, any> } },
    annotation: NodeAnnotation
  ): void {
    const metadata = this.getMetadata(node) || this.createDefaultMetadata();
    
    if (!metadata.annotations) {
      metadata.annotations = [];
    }
    
    metadata.annotations.push(annotation);
    this.setMetadata(node, metadata);
  }
  
  /**
   * Migrate old metadata format to new format
   */
  private static migrateOldMetadata(config: Record<string, any>): NodeMetadata | null {
    const hasOldFormat = 
      config._dslId !== undefined ||
      config._autoInjected !== undefined ||
      config._messageMode !== undefined ||
      config._textMode !== undefined ||
      config._bodyMode !== undefined ||
      config._queryMode !== undefined;
    
    if (!hasOldFormat) {
      return null;
    }
    
    // Migrate old format
    const metadata: NodeMetadata = {
      origin: {
        source: config._autoInjected ? 'system' : 'auto',
        approach: config._dslId ? 'dsl_generation' : 'auto_injected',
        stage: config._dslId ? 'dsl_compilation' : 'node_injection',
      },
    };
    
    if (config._dslId) {
      metadata.dsl = {
        dslId: config._dslId,
        category: 'data_source', // Default, will be determined from context
      };
    }
    
    if (config._autoInjected) {
      metadata.injection = {
        autoInjected: true,
        reason: 'System auto-injection',
      };
    }
    
    const aiGeneratedFields: string[] = [];
    if (config._messageMode === 'ai') aiGeneratedFields.push('message');
    if (config._textMode === 'ai') aiGeneratedFields.push('text');
    if (config._bodyMode === 'ai') aiGeneratedFields.push('body');
    if (config._queryMode === 'ai') aiGeneratedFields.push('query');
    
    if (aiGeneratedFields.length > 0) {
      metadata.aiMode = {
        aiGeneratedFields,
      };
    }
    
    return metadata;
  }
  
  /**
   * Create default metadata
   */
  private static createDefaultMetadata(): NodeMetadata {
    return {
      origin: {
        source: 'auto',
        approach: 'auto_injected',
        stage: 'workflow_building',
      },
    };
  }
  
  /**
   * Check if node has metadata
   */
  static hasMetadata(node: { data?: { config?: Record<string, any> } }): boolean {
    const config = node.data?.config || {};
    return !!(
      config[METADATA_PREFIXES.ORIGIN] ||
      config._dslId ||
      config._autoInjected ||
      config._messageMode ||
      config._textMode
    );
  }
  
  /**
   * Get origin source from node
   */
  static getOriginSource(node: { data?: { config?: Record<string, any> } }): NodeOriginSource {
    const metadata = this.getMetadata(node);
    return metadata?.origin?.source || 'auto';
  }
  
  /**
   * Get detection approach from node
   */
  static getDetectionApproach(node: { data?: { config?: Record<string, any> } }): DetectionApproach {
    const metadata = this.getMetadata(node);
    return metadata?.origin?.approach || 'auto_injected';
  }
  
  /**
   * Check if node is protected
   */
  static isProtected(node: { data?: { config?: Record<string, any> } }): boolean {
    const metadata = this.getMetadata(node);
    return metadata?.protected || false;
  }
  
  /**
   * Get annotations from node
   */
  static getAnnotations(node: { data?: { config?: Record<string, any> } }): NodeAnnotation[] {
    const metadata = this.getMetadata(node);
    return metadata?.annotations || [];
  }
}
