/**
 * Pipeline Contracts — Single Source of Truth for Stage Input/Output Types
 *
 * All four stages of WorkflowGenerationPipeline communicate exclusively
 * through these typed contracts. No stage reads state from a non-adjacent stage.
 *
 * Stage flow:
 *   UserPrompt → Stage1Output → Stage2Output → Stage3Output → UI
 */

import type { Workflow, WorkflowSummaryV2 } from './ai-types';
import type { FieldFillMode, FieldOwnershipClass } from './unified-node-contract';
import type { WorkflowBuildManifestV1 } from './workflow-build-manifest';
import type { CapabilityOptionStep } from '../../services/ai/stages/capability-selection-stage';
import type { StructuredIntent } from '../../services/ai/stages/intent-stage';
import type { SelectedNode, ValidationIssue } from '../../services/ai/system-prompt-builder';

// ─── StageTrace ───────────────────────────────────────────────────────────────

/** Appended to every pipeline response — success and failure. */
export interface StageTrace {
  stage: string;
  startedAt: number;
  completedAt: number;
  durationMs: number;
  inputSummary: string;
  outputSummary: string;
  llmCall?: {
    model: string;
    temperature: number;
    promptTokens: number;
    completionTokens: number;
  };
  error?: string;
}

// ─── Structural Prompt types ──────────────────────────────────────────────────

/** One numbered step in the human-readable workflow description. */
export interface StructuralStep {
  stepNumber: number;
  /** Canonical registry type — never shown to user. */
  nodeType: string;
  /** UnifiedNodeRegistry.label — always shown to user instead of nodeType. */
  displayName: string;
  /** What this step does in the context of the user's goal. */
  description: string;
}

/** Describes one branching condition and its two outcomes. */
export interface StructuralCondition {
  branchNodeType: string;
  trueOutcome: string;
  falseOutcome: string;
}

/**
 * Human-readable, structured description of the workflow that will be built.
 * Generated by StructuralPromptGenerator — registry-driven, no Gemini call.
 * Shown to user before graph construction begins.
 */
export interface StructuralPrompt {
  /** Full plain-English description, max 4000 chars. */
  text: string;
  steps: StructuralStep[];
  conditions: StructuralCondition[];
  /** First line shown to user — describes the trigger event. */
  triggerDescription: string;
  /** Last line shown to user — describes the terminal action. */
  terminalAction: string;
}

/** Input to StructuralPromptGenerator.generate(). */
export interface StructuralPromptInput {
  resolvedNodes: SelectedNode[];
  structuredIntent: StructuredIntent;
  /** stepId → selected node types from Node_Selection_UI. */
  capabilitySelections: Record<string, string[]>;
}

// ─── Field Ownership ──────────────────────────────────────────────────────────

/** Per-field ownership state held in the UI after Stage 3 delivers the workflow. */
export interface FieldOwnershipState {
  mode: 'user' | 'ai_built' | 'ai_runtime';
  /** Current displayed value. */
  value: unknown;
  /** Original AI-generated value from buildManifest — used to restore when user clicks "AI-built". */
  aiBuiltValue: unknown;
}

/**
 * nodeId → fieldName → ownership entry.
 * Built by BackendFinalizer and delivered to UI as part of Stage3Output.
 * Read-only after Stage 3 completes.
 */
export type FieldOwnershipMap = Record<
  string,
  Record<
    string,
    {
      mode: FieldOwnershipState['mode'];
      fillMode: FieldFillMode;
      ownership: FieldOwnershipClass;
    }
  >
>;

// ─── Stage Output Contracts ───────────────────────────────────────────────────

/**
 * Stage 1 output / Stage 2 input.
 * Produced after: intent → capability selection → node selection → structural prompt.
 */
export interface Stage1Output {
  structuredIntent: StructuredIntent;
  selectedNodes: SelectedNode[];
  /** Non-empty only when at least one use case was ambiguous. */
  capabilityOptions: CapabilityOptionStep[];
  /** stepId → user-selected node types (empty when no UI interaction occurred). */
  appliedCapabilitySelectionsByStep: Record<string, string[]>;
  /** Structural summary derived from reconciled graph preview. */
  summaryV2?: WorkflowSummaryV2;
  stageTrace: StageTrace[];
}

/**
 * Stage 2 output / Stage 3 input.
 * Produced after: StructuralPromptGenerator.generate() + user confirmation.
 */
export interface Stage2Output {
  /** Confirmed by user — frozen after this point. */
  structuralPrompt: StructuralPrompt;
  selectedNodes: SelectedNode[];
  structuredIntent: StructuredIntent;
  stageTrace: StageTrace[];
}

/**
 * Stage 3 output / Stage 4 (UI) input.
 * Produced after: BackendFinalizer.finalize() completes all internal steps.
 * The workflow is structurally valid, fully annotated, and ready for display.
 */
export interface Stage3Output {
  /** Structurally valid DAG — passes validateWorkflow() with no errors. */
  workflow: Workflow;
  /** Sealed build manifest — fieldOwnershipSnapshot is frozen (Object.freeze). */
  buildManifest: WorkflowBuildManifestV1;
  /** nodeId → fieldName → ownership entry for every field of every node. */
  fieldOwnershipMap: FieldOwnershipMap;
  /** Warning-severity issues only — hard errors block delivery. */
  validationIssues: ValidationIssue[];
  stageTrace: StageTrace[];
}

// ─── Error Response ───────────────────────────────────────────────────────────

export type PipelineErrorCode =
  | 'ORCHESTRATOR_VALIDATION_FAILED'
  | 'INTENT_FAILED'
  | 'NO_VALID_NODES'
  | 'INVALID_LLM_RESPONSE'
  | 'CAPABILITY_SELECTION_FAILED'
  | 'STRUCTURAL_PROMPT_FAILED'
  | 'CYCLE_DETECTED';

/**
 * Returned when any stage fails.
 * stageTrace contains entries only up to and including the failing stage.
 */
export interface PipelineErrorResponse {
  ok: false;
  error: PipelineErrorCode;
  message: string;
  /** Present only for ORCHESTRATOR_VALIDATION_FAILED. */
  violations?: string[];
  stageTrace: StageTrace[];
  correlationId: string;
}

// ─── Save Payload ─────────────────────────────────────────────────────────────

/**
 * Shape sent to the backend when the user saves the workflow.
 * fieldOwnershipOverrides contains only fields where the user changed
 * from the build-time default — the backend merges with buildManifest.fieldOwnershipSnapshot.
 */
export interface WorkflowSavePayload {
  workflow: Workflow;
  /** nodeId → fieldName → current mode (user-changed fields only). */
  fieldOwnershipOverrides: Record<string, Record<string, FieldOwnershipState['mode']>>;
}

// ─── Pipeline Input ───────────────────────────────────────────────────────────

/** Input to WorkflowGenerationPipeline.run(). */
export interface PipelineInput {
  userPrompt: string;
  userId: string;
  correlationId?: string;
  /** User selections from Node_Selection_UI — stepId → selected node types. */
  capabilitySelectionsByStep?: Record<string, string[]>;
  /** When set, node selection is filtered to these registry types. */
  mandatoryNodeTypes?: string[];
  /** Existing workflow for continuation requests — config values are merged. */
  existingWorkflow?: Workflow;
  /** Called after each named pipeline stage completes. Never throws. */
  onStageComplete?: (stageName: string, progress: number, log: string) => void;
}

/** Union result type for WorkflowGenerationPipeline.run(). */
export type PipelineResult = ({ ok: true } & Stage3Output) | PipelineErrorResponse;
