import { describe, expect, it } from '@jest/globals';
import { buildCredentialWizardView, type CredentialStatusRow } from '../wizard-credential-view';
import type { ComprehensiveNodeQuestion } from '../comprehensive-node-questions-generator';

const baseQuestion = (
  overrides: Partial<ComprehensiveNodeQuestion>,
): ComprehensiveNodeQuestion =>
  ({
    id: 'q_credential',
    text: 'Credential',
    type: 'password',
    nodeId: 'node_1',
    nodeType: 'generic_service',
    nodeLabel: 'Generic Service',
    fieldName: 'apiKey',
    category: 'credential',
    required: true,
    askOrder: 0,
    ...overrides,
  }) as ComprehensiveNodeQuestion;

describe('wizard credential view ownership fallback contract', () => {
  it('includes ownership-class credential rows without forcing direct credential input', () => {
    const questions: ComprehensiveNodeQuestion[] = [
      baseQuestion({
        id: 'q_legacy_secret',
        text: '',
        nodeId: 'sendgrid_1',
        nodeType: 'sendgrid_email',
        nodeLabel: 'SendGrid',
        fieldName: 'clientSecret',
        category: 'configuration',
        ownershipClass: 'credential',
        askOrder: 0,
      }),
      baseQuestion({
        id: 'q_google_oauth',
        text: 'Google OAuth account',
        nodeId: 'gmail_1',
        nodeType: 'google_gmail',
        nodeLabel: 'Gmail',
        fieldName: 'authType',
        ownershipUiMode: 'locked',
        askOrder: 0,
      }),
    ];
    const statuses: CredentialStatusRow[] = [
      {
        nodeId: 'sendgrid_1',
        credentialId: 'sendgrid_client_secret',
        displayName: 'SendGrid Client Secret',
        status: 'required_missing',
      },
      {
        nodeId: 'gmail_1',
        credentialId: 'google',
        displayName: 'Google OAuth',
        status: 'resolved_connected',
      },
    ];

    const { rows } = buildCredentialWizardView(questions, statuses);

    expect(rows).toHaveLength(2);
    expect(rows.find((row) => row.questionId === 'q_legacy_secret')).toEqual(
      expect.objectContaining({
        displayTitle: 'client Secret',
        subtitle: 'SendGrid \u00b7 clientSecret',
        kind: 'token',
        status: 'required_missing',
        ownershipSummary: 'user',
        requiresInput: false,
      }),
    );
    expect(rows.find((row) => row.questionId === 'q_google_oauth')).toEqual(
      expect.objectContaining({
        kind: 'oauth',
        status: 'resolved_connected',
        ownershipSummary: 'locked',
        requiresInput: false,
      }),
    );
  });

  it('clips verbose credential descriptions when they are used as subtitles', () => {
    const longDescription = `Paste the token generated by the workspace security console. ${'A'.repeat(320)}`;
    const questions: ComprehensiveNodeQuestion[] = [
      baseQuestion({
        id: 'q_long_description',
        text: 'Workspace token',
        description: longDescription,
        nodeId: 'notion_1',
        nodeType: 'notion',
        nodeLabel: 'Notion',
        fieldName: 'accessToken',
      }),
    ];

    const { rows } = buildCredentialWizardView(questions, []);

    expect(rows[0]).toEqual(
      expect.objectContaining({
        displayTitle: 'Workspace token',
        subtitle: longDescription.slice(0, 280),
        status: 'not_required',
        requiresInput: false,
      }),
    );
    expect(rows[0].subtitle).toHaveLength(280);
  });
});
