/**
 * Structured Error Codes
 * 
 * ✅ CRITICAL: Standardized error codes for frontend mapping
 * 
 * Instead of raw messages, use structured codes that frontend can map to UX.
 */

export enum ErrorCode {
  // Graph errors
  GRAPH_PARSE_ERROR = 'GRAPH_PARSE_ERROR',
  GRAPH_INVALID_STRUCTURE = 'GRAPH_INVALID_STRUCTURE',
  GRAPH_MISSING_NODES = 'GRAPH_MISSING_NODES',
  GRAPH_MISSING_EDGES = 'GRAPH_MISSING_EDGES',
  GRAPH_DUPLICATE_NODE_ID = 'GRAPH_DUPLICATE_NODE_ID',
  GRAPH_INVALID_EDGE_REFERENCE = 'GRAPH_INVALID_EDGE_REFERENCE',

  // Node errors
  NODE_SCHEMA_INVALID = 'NODE_SCHEMA_INVALID',
  NODE_TYPE_UNKNOWN = 'NODE_TYPE_UNKNOWN',
  NODE_MISSING_REQUIRED_FIELD = 'NODE_MISSING_REQUIRED_FIELD',
  NODE_INVALID_FIELD_TYPE = 'NODE_INVALID_FIELD_TYPE',

  // Input errors
  MISSING_INPUT = 'MISSING_INPUT',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_INPUT_FORMAT = 'INVALID_INPUT_FORMAT',
  INPUT_FIELD_NOT_IN_SCHEMA = 'INPUT_FIELD_NOT_IN_SCHEMA',
  INPUT_CREDENTIAL_FIELD_REJECTED = 'INPUT_CREDENTIAL_FIELD_REJECTED',

  // Credential errors
  MISSING_CREDENTIAL = 'MISSING_CREDENTIAL',
  INVALID_CREDENTIAL_FORMAT = 'INVALID_CREDENTIAL_FORMAT',
  CREDENTIAL_INJECTION_FAILED = 'CREDENTIAL_INJECTION_FAILED',
  OAUTH_NOT_CONNECTED = 'OAUTH_NOT_CONNECTED',
  GOOGLE_AUTH_REQUIRED = 'GOOGLE_AUTH_REQUIRED',

  // Workflow errors
  WORKFLOW_NOT_FOUND = 'WORKFLOW_NOT_FOUND',
  WORKFLOW_INVALID_PHASE = 'WORKFLOW_INVALID_PHASE',
  WORKFLOW_ALREADY_EXECUTING = 'WORKFLOW_ALREADY_EXECUTING',
  WORKFLOW_NOT_READY = 'WORKFLOW_NOT_READY',
  WORKFLOW_VALIDATION_FAILED = 'WORKFLOW_VALIDATION_FAILED',

  // Phase errors
  PHASE_LOCKED = 'PHASE_LOCKED',
  PHASE_MISMATCH = 'PHASE_MISMATCH',
  INVALID_PHASE = 'INVALID_PHASE',
  DUPLICATE_ATTACH_CALL = 'DUPLICATE_ATTACH_CALL',

  // Execution errors
  EXECUTION_NOT_READY = 'EXECUTION_NOT_READY',
  EXECUTION_MISSING_INPUTS = 'EXECUTION_MISSING_INPUTS',
  EXECUTION_MISSING_CREDENTIALS = 'EXECUTION_MISSING_CREDENTIALS',
  EXECUTION_FAILED = 'EXECUTION_FAILED',
  RUN_ALREADY_ACTIVE = 'RUN_ALREADY_ACTIVE',
  EXECUTION_TIMEOUT = 'EXECUTION_TIMEOUT',

  // Generic errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',
}

export interface StructuredError {
  code: ErrorCode;
  message: string;
  details?: any;
  recoverable?: boolean;
}

export function createError(
  code: ErrorCode,
  message: string,
  details?: any,
  recoverable: boolean = false
): StructuredError {
  return {
    code,
    message,
    details,
    recoverable,
  };
}

export function isRecoverableError(error: StructuredError): boolean {
  return error.recoverable === true;
}
