/**
 * SEMANTIC NODE EQUIVALENCE REGISTRY
 * 
 * This is the SINGLE SOURCE OF TRUTH for semantic node equivalence.
 * 
 * Architecture Rules:
 * 1. ALL semantic equivalence logic MUST be defined here
 * 2. All layers (intent, DSL, auto-repair, optimizer, validation, sanitization) MUST use this registry
 * 3. Operation-aware: same node type can be equivalent in one context, not another
 * 4. Extensible: easy to add new equivalences
 * 5. Always keeps canonical nodes, removes semantic duplicates
 * 
 * This ensures:
 * - No parallel branches (semantic duplicates removed)
 * - No orphaned nodes (equivalence checked before injection)
 * - Universal solution for ALL node types
 * - Permanent fixes apply to ALL workflows
 */

import { unifiedNodeRegistry } from './unified-node-registry';
import { unifiedNormalizeNodeTypeString } from '../../core/utils/unified-node-type-normalizer';
import { semanticEquivalenceAutoGenerator } from './semantic-equivalence-auto-generator';

/**
 * Semantic Equivalence Definition
 * 
 * Defines which node types are semantically equivalent for a given operation.
 */
export interface SemanticEquivalenceDefinition {
  /**
   * Canonical node type (the one to KEEP)
   * This is the preferred/standard node type
   */
  canonical: string;
  
  /**
   * List of semantically equivalent node types (the ones to REMOVE if canonical exists)
   */
  equivalents: string[];
  
  /**
   * Operation context (optional)
   * If specified, equivalence only applies when nodes perform this operation
   * If not specified, equivalence applies for all operations
   */
  operation?: string;
  
  /**
   * Category context (optional)
   * If specified, equivalence only applies when nodes are in this category
   */
  category?: string;
  
  /**
   * Priority: higher priority canonical types are preferred when multiple exist
   */
  priority?: number;
}

/**
 * Semantic Node Equivalence Registry
 * 
 * Central registry for all semantic node equivalences.
 */
export class SemanticNodeEquivalenceRegistry {
  private static instance: SemanticNodeEquivalenceRegistry;
  private equivalences: Map<string, SemanticEquivalenceDefinition> = new Map();
  
  private constructor() {
    console.log('[SemanticNodeEquivalenceRegistry] 🏗️  Initializing Semantic Node Equivalence Registry...');
    
    // STEP 1: Initialize manual equivalences (explicit, high priority)
    this.initializeEquivalences();
    const manualCount = this.equivalences.size;
    
    // STEP 2: ✅ PRODUCTION-READY: Auto-generate equivalences for ALL nodes
    // This ensures comprehensive coverage for all node types
    const autoGenerated = semanticEquivalenceAutoGenerator.generateComprehensiveEquivalences();
    autoGenerated.forEach(def => {
      // Only add if not already defined (manual takes priority)
      const key = `${def.canonical}:${def.operation || '*'}:${def.category || '*'}`;
      if (!this.equivalences.has(key)) {
        this.registerEquivalence(def);
      }
    });
    
    const totalCount = this.equivalences.size;
    const autoCount = totalCount - manualCount;
    
    console.log(`[SemanticNodeEquivalenceRegistry] ✅ Initialized with ${totalCount} equivalence definition(s)`);
    console.log(`[SemanticNodeEquivalenceRegistry]   - Manual: ${manualCount}, Auto-generated: ${autoCount}`);
  }
  
  static getInstance(): SemanticNodeEquivalenceRegistry {
    if (!SemanticNodeEquivalenceRegistry.instance) {
      SemanticNodeEquivalenceRegistry.instance = new SemanticNodeEquivalenceRegistry();
    }
    return SemanticNodeEquivalenceRegistry.instance;
  }
  
  /**
   * Initialize semantic equivalences
   * 
   * This is where ALL semantic equivalences are defined.
   * Add new equivalences here as you discover them.
   */
  private initializeEquivalences(): void {
    // ============================================
    // SOCIAL MEDIA EQUIVALENCES
    // ============================================
    
    // Instagram: canonical = instagram, equivalents = instagram_post, post_to_instagram
    this.registerEquivalence({
      canonical: 'instagram',
      equivalents: ['instagram_post', 'post_to_instagram', 'instagram_api'],
      operation: 'create',
      category: 'communication',
      priority: 10
    });
    
    // LinkedIn: canonical = linkedin, equivalents = linkedin_post, post_to_linkedin
    this.registerEquivalence({
      canonical: 'linkedin',
      equivalents: ['linkedin_post', 'post_to_linkedin', 'linkedin_api'],
      operation: 'create',
      category: 'communication',
      priority: 10
    });
    
    // Twitter: canonical = twitter, equivalents = twitter_post, post_to_twitter
    this.registerEquivalence({
      canonical: 'twitter',
      equivalents: ['twitter_post', 'post_to_twitter', 'twitter_api'],
      operation: 'create',
      category: 'communication',
      priority: 10
    });
    
    // Facebook: canonical = facebook, equivalents = facebook_post, post_to_facebook
    this.registerEquivalence({
      canonical: 'facebook',
      equivalents: ['facebook_post', 'post_to_facebook', 'facebook_api'],
      operation: 'create',
      category: 'communication',
      priority: 10
    });
    
    // HTTP Request for social posting: equivalent to social nodes when operation = create
    this.registerEquivalence({
      canonical: 'instagram', // Prefer instagram over http_request
      equivalents: ['http_request'],
      operation: 'create',
      category: 'communication',
      priority: 5 // Lower priority - prefer specific social nodes
    });
    
    // ============================================
    // AI EQUIVALENCES
    // ============================================
    
    // AI Chat Model: canonical = ai_chat_model, equivalents = ollama, openai_gpt, etc.
    this.registerEquivalence({
      canonical: 'ai_chat_model',
      equivalents: ['ollama', 'openai_gpt', 'anthropic_claude', 'google_gemini', 'ai_service'],
      operation: 'process', // or 'transform', 'generate', 'summarize'
      category: 'ai',
      priority: 10
    });
    
    // AI Service: can be equivalent to ai_chat_model when operation matches
    this.registerEquivalence({
      canonical: 'ai_chat_model',
      equivalents: ['ai_service', 'ai_agent'],
      operation: 'process',
      category: 'ai',
      priority: 8
    });
    
    // ============================================
    // EMAIL EQUIVALENCES
    // ============================================
    
    // Gmail: canonical = google_gmail, equivalents = gmail, email (when operation = send)
    this.registerEquivalence({
      canonical: 'google_gmail',
      equivalents: ['gmail', 'email'],
      operation: 'send',
      category: 'communication',
      priority: 10
    });
    
    // ============================================
    // DATABASE EQUIVALENCES
    // ============================================
    
    // PostgreSQL: canonical = postgres, equivalents = postgresql, database_write
    this.registerEquivalence({
      canonical: 'postgres',
      equivalents: ['postgresql', 'database_write'],
      operation: 'write',
      category: 'data',
      priority: 10
    });
    
    // ============================================
    // HTTP/API EQUIVALENCES
    // ============================================
    
    // HTTP Request: canonical = http_request, equivalents = rest_api, api_call
    this.registerEquivalence({
      canonical: 'http_request',
      equivalents: ['rest_api', 'api_call', 'http_api'],
      operation: 'fetch', // or 'get', 'post', etc.
      category: 'data',
      priority: 10
    });
    
    // ============================================
    // CRM EQUIVALENCES
    // ============================================
    
    // Salesforce: canonical = salesforce, equivalents = salesforce_crm, salesforce_api
    this.registerEquivalence({
      canonical: 'salesforce',
      equivalents: ['salesforce_crm', 'salesforce_api'],
      operation: 'create', // or 'update', 'read'
      category: 'data',
      priority: 10
    });
    
    // ============================================
    // Add more equivalences as you discover them
    // ============================================
  }
  
  /**
   * Register a semantic equivalence definition
   */
  private registerEquivalence(definition: SemanticEquivalenceDefinition): void {
    // Store by canonical type for fast lookup
    const key = `${definition.canonical}:${definition.operation || '*'}:${definition.category || '*'}`;
    this.equivalences.set(key, definition);
    
    // Also store reverse mapping (equivalent -> canonical) for fast lookup
    for (const equivalent of definition.equivalents) {
      const reverseKey = `${equivalent}:${definition.operation || '*'}:${definition.category || '*'}`;
      if (!this.equivalences.has(reverseKey)) {
        // Store reverse mapping with lower priority
        this.equivalences.set(reverseKey, {
          canonical: definition.canonical,
          equivalents: [],
          operation: definition.operation,
          category: definition.category,
          priority: (definition.priority || 0) - 1
        });
      }
    }
  }
  
  /**
   * Get canonical node type for a given node type
   * 
   * Returns the canonical type if equivalence exists, otherwise returns the input type
   * 
   * ✅ PRODUCTION-READY: Handles null/undefined inputs gracefully
   */
  getCanonicalType(nodeType: string, operation?: string, category?: string): string {
    // ✅ PRODUCTION-READY: Validate input
    if (!nodeType || typeof nodeType !== 'string') {
      console.warn(`[SemanticNodeEquivalenceRegistry] ⚠️  Invalid nodeType input: ${nodeType}, returning as-is`);
      return nodeType || '';
    }
    
    const normalized = unifiedNormalizeNodeTypeString(nodeType).toLowerCase();
    
    // Try exact match first (with operation and category)
    if (operation && category) {
      const key = `${normalized}:${operation}:${category}`;
      const def = this.equivalences.get(key);
      if (def) {
        return def.canonical;
      }
    }
    
    // Try with operation only
    if (operation) {
      const key = `${normalized}:${operation}:*`;
      const def = this.equivalences.get(key);
      if (def) {
        return def.canonical;
      }
    }
    
    // Try with category only
    if (category) {
      const key = `${normalized}:*:${category}`;
      const def = this.equivalences.get(key);
      if (def) {
        return def.canonical;
      }
    }
    
    // Try wildcard match (any operation, any category)
    const key = `${normalized}:*:*`;
    const def = this.equivalences.get(key);
    if (def) {
      return def.canonical;
    }
    
    // Also check if this node type IS a canonical type
    // Look through all definitions to see if this is a canonical
    for (const [key, def] of this.equivalences.entries()) {
      if (def.canonical.toLowerCase() === normalized) {
        return def.canonical; // Return as-is (it's already canonical)
      }
    }
    
    // No equivalence found - return original type
    return nodeType;
  }
  
  /**
   * Check if two node types are semantically equivalent
   * 
   * ✅ PRODUCTION-READY: Handles null/undefined inputs gracefully
   */
  areEquivalent(
    nodeType1: string,
    nodeType2: string,
    operation?: string,
    category?: string
  ): boolean {
    // ✅ PRODUCTION-READY: Validate inputs
    if (!nodeType1 || !nodeType2) {
      return false; // Can't be equivalent if either is missing
    }
    
    const canonical1 = this.getCanonicalType(nodeType1, operation, category);
    const canonical2 = this.getCanonicalType(nodeType2, operation, category);
    
    return canonical1.toLowerCase() === canonical2.toLowerCase();
  }
  
  /**
   * Get all semantically equivalent node types for a given node type
   */
  getEquivalents(nodeType: string, operation?: string, category?: string): string[] {
    const normalized = unifiedNormalizeNodeTypeString(nodeType).toLowerCase();
    const equivalents: string[] = [];
    
    // Find all definitions that include this node type
    for (const [key, def] of this.equivalences.entries()) {
      // Check if this node type is the canonical
      if (def.canonical.toLowerCase() === normalized) {
        // Check operation and category match
        if (operation && def.operation && def.operation !== operation) continue;
        if (category && def.category && def.category !== category) continue;
        
        equivalents.push(...def.equivalents);
      }
      
      // Check if this node type is in the equivalents list
      if (def.equivalents.some(eq => eq.toLowerCase() === normalized)) {
        // Check operation and category match
        if (operation && def.operation && def.operation !== operation) continue;
        if (category && def.category && def.category !== category) continue;
        
        equivalents.push(def.canonical);
        // Also add other equivalents (they're all equivalent to each other)
        equivalents.push(...def.equivalents.filter(eq => eq.toLowerCase() !== normalized));
      }
    }
    
    // Remove duplicates and return
    return [...new Set(equivalents)];
  }
  
  /**
   * Check if a node type is a semantic duplicate of any node in a list
   * 
   * Returns the existing node that is semantically equivalent, or null
   * 
   * ✅ PRODUCTION-READY: Handles null/undefined inputs gracefully
   */
  findSemanticDuplicate(
    nodeType: string,
    existingNodeTypes: string[],
    operation?: string,
    category?: string
  ): string | null {
    // ✅ PRODUCTION-READY: Validate inputs
    if (!nodeType || !Array.isArray(existingNodeTypes) || existingNodeTypes.length === 0) {
      return null;
    }
    
    const normalized = unifiedNormalizeNodeTypeString(nodeType).toLowerCase();
    const canonical = this.getCanonicalType(nodeType, operation, category);
    
    for (const existingType of existingNodeTypes) {
      const existingNormalized = unifiedNormalizeNodeTypeString(existingType).toLowerCase();
      const existingCanonical = this.getCanonicalType(existingType, operation, category);
      
      // Check if they're equivalent
      if (canonical.toLowerCase() === existingCanonical.toLowerCase()) {
        // They're semantically equivalent
        // Prefer the canonical type
        if (existingNormalized === canonical.toLowerCase()) {
          return existingType; // Existing is canonical, prefer it
        }
        if (normalized === canonical.toLowerCase()) {
          return existingType; // New is canonical, but existing exists, so return existing
        }
        // Both are equivalents - prefer existing (don't add duplicate)
        return existingType;
      }
    }
    
    return null; // No semantic duplicate found
  }
  
  /**
   * Get operation and category from node (for context-aware equivalence checking)
   */
  getNodeContext(node: { type?: string; data?: { type?: string; config?: Record<string, any> } }): {
    operation?: string;
    category?: string;
  } {
    const nodeType = unifiedNormalizeNodeTypeString(node.type || node.data?.type || '');
    const nodeDef = unifiedNodeRegistry.get(nodeType);
    
    const operation = node.data?.config?.operation as string | undefined;
    const category = nodeDef?.category;
    
    return { operation, category };
  }
}

// Export singleton instance
export const semanticNodeEquivalenceRegistry = SemanticNodeEquivalenceRegistry.getInstance();
