/**
 * AI Field Detector
 * 
 * ✅ ROOT-LEVEL ARCHITECTURE: Detects which fields should be AI-generated
 * Works for ALL nodes automatically based on field names and node types
 */

import { WorkflowNode } from '../../core/types/ai-types';
import { nodeLibrary } from '../nodes/node-library';
import { unifiedNormalizeNodeType, unifiedNormalizeNodeTypeString } from '../../core/utils/unified-node-type-normalizer';

export interface AIFieldDetection {
  fieldName: string;
  shouldAutoGenerate: boolean;
  reason: string;
  fieldType: string;
}

/**
 * AI Field Detector
 * Determines which fields should be auto-generated by AI
 */
export class AIFieldDetector {
  /**
   * Detect if a field should be AI-generated
   * 
   * Criteria:
   * - Field name matches AI-generatable patterns (message, subject, body, etc.)
   * - Field type is string (not dropdown, not JSON)
   * - Node type supports AI generation (communication, AI nodes, etc.)
   */
  shouldAutoGenerate(
    fieldName: string,
    nodeType: string,
    fieldSchema?: any
  ): boolean {
    const fieldLower = fieldName.toLowerCase();
    const nodeTypeLower = nodeType.toLowerCase();
    
    // ✅ ROOT-LEVEL: Text fields that benefit from AI generation
    const aiGeneratableFields = [
      'message', 'subject', 'body', 'heading', 'title',
      'content', 'text', 'description', 'summary',
      'prompt', 'input', 'query', 'question',
      'email', 'to', 'from', 'cc', 'bcc',
      'channel', 'recipient', 'address'
    ];
    
    // ✅ CRITICAL FIX: HTTP Request nodes - headers and body should be AI-generated
    // These are JSON/object fields but should still be AI-generated
    if (nodeTypeLower.includes('http_request') || nodeTypeLower.includes('http_post')) {
      if (fieldLower === 'headers' || fieldLower === 'body') {
        // Headers and body for HTTP Request should be AI-generated
        // They're JSON/object fields but AI will generate the structure
        return true;
      }
    }
    
    // ✅ ROOT-LEVEL: Check if field name matches AI-generatable patterns
    const isGeneratableField = aiGeneratableFields.some(f => 
      fieldLower.includes(f) || fieldLower === f
    );
    
    if (!isGeneratableField) {
      return false;
    }
    
    // ✅ ROOT-LEVEL: For text fields (string/text) - standard check
    // ✅ CRITICAL FIX: For HTTP Request headers/body (JSON/object) - allow AI generation
    if (fieldSchema) {
      const fieldType = fieldSchema.type || 'string';
      
      // Allow JSON/object fields for HTTP Request headers and body
      if ((fieldType === 'object' || fieldType === 'json') && 
          (nodeTypeLower.includes('http_request') || nodeTypeLower.includes('http_post')) &&
          (fieldLower === 'headers' || fieldLower === 'body')) {
        // These are JSON fields but should be AI-generated
        return true;
      }
      
      // For other fields, only allow string/text
      if (fieldType !== 'string' && fieldType !== 'text') {
        return false; // Not a text field
      }
      
      // ✅ ROOT-LEVEL: Skip if field has options (dropdowns are user-selected)
      if (fieldSchema.options && Array.isArray(fieldSchema.options) && fieldSchema.options.length > 0) {
        return false; // Dropdown - user must select
      }
      
      // ✅ ROOT-LEVEL: Skip if field has examples that are meant for selection
      if (fieldSchema.examples && Array.isArray(fieldSchema.examples) && fieldSchema.examples.length > 0) {
        // If examples are short strings, might be dropdown options
        const allShortStrings = fieldSchema.examples.every((ex: any) => 
          typeof ex === 'string' && ex.length < 50
        );
        if (allShortStrings && fieldSchema.examples.length <= 10) {
          return false; // Likely dropdown options
        }
      }
    }
    
    // ✅ ROOT-LEVEL: Node type check - some nodes always benefit from AI
    const aiFriendlyNodes = [
      'gmail', 'email', 'slack', 'discord', 'telegram',
      'ai_chat_model', 'ai_agent', 'ai_service',
      'notification', 'message', 'communication'
    ];
    
    const isAIFriendlyNode = aiFriendlyNodes.some(n => nodeTypeLower.includes(n));
    
    // ✅ ROOT-LEVEL: Always allow AI generation for AI-friendly nodes
    // For other nodes, only if field name matches patterns
    return isAIFriendlyNode || isGeneratableField;
  }
  
  /**
   * Detect all AI-generatable fields for a node
   */
  detectAIFields(node: WorkflowNode): AIFieldDetection[] {
    const nodeType = unifiedNormalizeNodeType(node);
    const schema = nodeLibrary.getSchema(nodeType);
    
    if (!schema || !schema.configSchema) {
      return [];
    }
    
    const requiredFields = schema.configSchema.required || [];
    const optionalFields = Object.keys(schema.configSchema.optional || {});
    const allFields = [...requiredFields, ...optionalFields];
    
    const detections: AIFieldDetection[] = [];
    
    for (const fieldName of allFields) {
      const fieldSchema = schema.configSchema.optional?.[fieldName];
      const shouldGenerate = this.shouldAutoGenerate(fieldName, nodeType, fieldSchema);
      
      if (shouldGenerate) {
        detections.push({
          fieldName,
          shouldAutoGenerate: true,
          reason: `Field "${fieldName}" is a text field that benefits from AI generation`,
          fieldType: fieldSchema?.type || 'string',
        });
      }
    }
    
    return detections;
  }
}

// Export singleton instance
export const aiFieldDetector = new AIFieldDetector();
